# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "3560f93cd2a27ee36a3e40313ca05af6"
name = "tyz-actions-access-ri"
application_url = "https://tyz-actions-access.vercel.app/"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes,write_theme_code,read_files,write_files"

[auth]
redirect_urls = [
  "https://tyz-actions-access.vercel.app/auth/callback",
  "https://tyz-actions-access.vercel.app/auth/shopify/callback",
  "https://tyz-actions-access.vercel.app/api/auth/callback"
]
