# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "b18aed6291871ae34cb063472bd485fb"
name = "tyz-actions-access"
application_url = "https://tyz-actions-access.vercel.app/"
embedded = true

[webhooks]
api_version = "2025-10"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_themes,write_themes,write_theme_code,read_files,write_files"
optional_scopes = [ ]
use_legacy_install_flow = false

[auth]
redirect_urls = [
  "https://tyz-actions-access.vercel.app/auth/callback",
  "https://tyz-actions-access.vercel.app/auth/shopify/callback",
  "https://tyz-actions-access.vercel.app/api/auth/callback"
]

[build]
automatically_update_urls_on_dev = true
